---
title: "Getting Zillow data"
author: "Zeping"
date: "2019???10???19???"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

libraries
```{r}
library("ZillowR")
library("jsonlite")
library('rvest')
library('XML')
```

set up the API key
```{r}
zwsid <- "X1-ZWz1hetbmyoqa3_13bwv"
set_zillow_web_service_id('X1-ZWz1hetbmyoqa3_13bwv')
```

request and check if succeed
```{r}
for (i in 1000:9999){
  test_addr_temp<-GetSearchResults(address=paste(i,"Avon Park Dr"), citystatezip = 'Flint, MI')
  if test_addr_temp$message$code ==0{
    zpid<-xmlToDataFrame(nodes = getNodeSet(test_addr$response, "//zpid"), stringsAsFactors = FALSE)
    Zestimate<-xmlToDataFrame(nodes = getNodeSet(test_addr$response, "//zestimate"), stringsAsFactors = FALSE)
    data.frame()
  }
  
}

```
6 records for "* Brown St"

Try to parse the XMLNode and get "zpid"
  reference: the document of "XML" package https://cran.r-project.org/web/packages/XML/XML.pdf
```{r}
xmllist<-xmlParse(test_addr$response)
zpid<-xmlToDataFrame(nodes = getNodeSet(test_addr$response, "//zpid"), stringsAsFactors = FALSE)
#success: subset nodes
xmllist<-xmlToList(test_addr$response)
#sucess: all, but 
xmllist[[2]]
xmllist[[3]]
pagexml2<-htmlTreeParse(test,encoding="utf-8",useInternalNodes = TRUE,trim=TRUE)
nds <- xml(test_addr$response, xpath = '//zpid')
```

Try "getChart" to see if we can get historical data
```{r}
chart<-GetChart(zpid = 190340363)
chart_url<-xmlToDataFrame(nodes=getNodeSet(chart$response,"//url"))
write.csv(chart_url,file='chart url example.csv')
```


GetZestmate
```{r}
class(zpid)
Zestimate<-apply(zpid,1,GetZestimate)
```

